### ISSUE TITLE
Question: throwing an error inside the reduce function

### ISSUE THREAD

**Issue by boaz0** [epicweb-dev/advanced-react-patterns#40]
Hey,

I was wondering are there any significant advantages to throwing an error inside the reducer function?
IMHO, it is a side effect and the reducer function should not have that.

I do see what you were trying to do there but I believe it is a bad user experience even though the developer was not careful and dispatched an event that's not handled by the reducer.

Thanks.

**Comment by vasilii-kovalev** [comment]
I also noticed this moment in some workshops. I worked with reducers (and switch-case statements) when worked with Redux mostly, and returned `state` by default. But we in team always created constants for action types, so we didn't have problems with incorrect ones passed. This problem even fades out completely when using TypeScript.

Maybe it is applicable when you need to check an idea and create a prototype very quickly (though it is not too hard to keep them in an object or as separate constants). Or when you implement `state reducer` pattern and its user refuses to use your `actionTypes` object :) And it's actually more explicit and allows you to find them problem earlier.

@kentcdodds, what's your opinion?

**Comment by kentcdodds** [comment]
This type of question is normally best for https://kcd.im/office-hours

If you have TypeScript then throwing is unnecessary because any typo will be caught by the type checker. If you don't though, it's important to fail loud and fast so that's why I throw the error. It's not expected that you would ship a codepath that runs the error in production, so the fact that it's a side-effect is not entirely relevant.

> And it's actually more explicit and allows you to find them problem earlier.

This is a good summary.

I hope that helps :)
